networks:
    pet-store-network:

name: "pet-store"

services:
    php:
        container_name: pet-store-php
        ports:
            - "8031:80"
        build:
            context: ..
            dockerfile: .docker/php/Dockerfile
        volumes:
            - ../:/var/www/app
            - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - pet-store-network
